name: pip_services_emailsettings
version: "1.0.0"
description: Email Settings microservice for Pip.Services in Dart. This microservice keeps settings of email recipients.
homepage: https://github.com/pip-services-users/pip-services-emailsettings-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pip_services3_commons: ">=1.0.5 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_data: ">=1.0.0 <2.0.0"
  pip_services3_mongodb: ">=1.0.2 <2.0.0"
  pip_services3_rpc: ">=1.0.2 <2.0.0"
  pip_services3_grpc: ">=1.0.0 <2.0.0"
  pip_services3_container: ">=1.0.0 <2.0.0"
  pip_clients_activities: ">=1.0.0 <2.0.0"
  pip_services_activities: ">=1.0.0 <2.0.0"  
  pip_clients_email: ">=1.0.0 <2.0.0"
  pip_services_email: ">=1.0.1 <2.0.0"
  pip_clients_msgtemplates: ">=1.0.0 <2.0.0"
  pip_services_msgtemplates: ">=1.0.0 <2.0.0"
  mongo_dart_query: "^0.4.1"
  http: "^0.12.0"
  angel_framework: ^2.1.1

dev_dependencies:
  test: '>=1.14.2 <2.0.0'
